
server:
  port: 9081

spring:
  application:
      name: kkt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kkt
    password: kkt
    url: jdbc:mysql://localhost/kkt?characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PRC
  jpa:
    show-sql: true
